apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-joi
  name: devops-joi
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: devops-joi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-joi
    spec:
      restartPolicy: Always
      initContainers:
      - name: devops-joi-migration
        image: 'devopsinterview_migration'
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: db-info
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: db-info
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USER
                name: db-info
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: db-info
      containers:
      - name: devops-joi-app
        image: 'devopsinterview_app'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: db-info
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: db-info
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USER
                name: db-info
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: db-info
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            httpHeaders:
              - name: Host
                value: devops.joi.toc-platform.com
            path: /diagnostic/liveness
            port: 80
            scheme: HTTP
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            httpHeaders:
              - name: Host
                value: devops.joi.toc-platform.com
            path: /diagnostic/readiness
            port: 80
            scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-joi-db
  name: devops-joi-db
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: devops-joi-db
  template:
    metadata:
      labels:
        app: devops-joi-db
    spec:
      restartPolicy: Always
      containers:
        - name: devops-joi-db
          image: 'mysql:8'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_ROOT_PASSWORD
                  name: db-info
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: db-info
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: db-info
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: db-info
